version: "3.5"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/prod.Dockerfile
    restart: always
    volumes:
      - ./backend:/go/src/github.com/skygate/wordspree
    ports:
      - 8003:8003

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 8002:8002
    restart: always